### PR TITLE
Ref/cleanup comments

### PR DESCRIPTION
**Pull request by GoonTwo**
- Commented a lot of the code so I could understand what was going on
- Changed the `for-in loop` to iterate over the object's keys. The Airbnb linter wanted it this way. This is towards the end of `Dashboard.jsx`

I will be better about commit messages and single focus pull requests moving forward

### CODE REVIEW

**Review by katm201 — COMMENTED** [review]
Generally looks good, but could you remove the 2 console.logs in 'client/src/containers/ScheduleTemplate.jsx'? 

Also, I appreciate the refactor, but how thoroughly did you test this out to make sure changing variable names didn't cause any unintended consequences? I'm inclined to leave their naming the way it was, even though they're bad, just in case it accidentally breaks something we can't see.

**Comment by GoonTwo** [comment]
Cleaned up the console logs.

I see where you are coming from on the concern, but If you look at the files you can see that it is defined when it is passed into the child component and it isn't used anywehre else after that excep inside the next component.

**Comment by GoonTwo** [comment]
Variable renaming has been taken out of the commit

**Review by katm201 — APPROVED** [review]
Thanks! Looks good and I appreciate all the comments explaining what's going on.

**Pull request merged**
